Update aws.yaml

diff --git a/.github/workflows/aws.yaml b/.github/workflows/aws.yaml
--- a/.github/workflows/aws.yaml
+++ b/.github/workflows/aws.yaml
@@ -48,9 +48,9 @@ jobs:
             --publish
           }
           function_deploy
-          # Retry logic
-          for i in {1..3}; do
-            function_deploy && break || sleep 30
+          # Retry logic with longer delay
+          for i in {1..5}; do
+            function_deploy && break || (echo "Retrying..."; sleep 60)
           done
 
       - name: Update function configuration with description
@@ -61,7 +61,7 @@ jobs:
             --description "${{ github.event.inputs.description }}"
           }
           function_update
-          # Retry logic
-          for i in {1..3}; do
-            function_update && break || sleep 30
+          # Retry logic with longer delay
+          for i in {1..5}; do
+            function_update && break || (echo "Retrying..."; sleep 60)
           done
